/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package configuracao;

import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Ana Julia
 */
public class AntigoCodigo extends javax.swing.JFrame {

    /**
     * Creates new form Codigo
     */
    public AntigoCodigo() {
        initComponents();
    }
   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Análise = new javax.swing.JLabel();
        httpd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        Análise.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Análise.setText("Análise");
        getContentPane().add(Análise);
        Análise.setBounds(160, 30, 70, 20);

        httpd.setText(" httpd");
        httpd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                httpdActionPerformed(evt);
            }
        });
        getContentPane().add(httpd);
        httpd.setBounds(130, 70, 110, 30);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-399)/2, (screenSize.height-324)/2, 399, 324);
    }// </editor-fold>//GEN-END:initComponents

    private void httpdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_httpdActionPerformed
        // TODO add your handling code here:
    
         AntigoLeitor t = new AntigoLeitor();
         String texto; 
        try {
            t.Ler();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(AntigoCodigo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(AntigoCodigo.class.getName()).log(Level.SEVERE, null, ex);
        }
         texto=t.leitor();
         
        AntigoLeitura l = new AntigoLeitura(texto);
        l.setVisible(true);
    }//GEN-LAST:event_httpdActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Análise;
    private javax.swing.JButton httpd;
    // End of variables declaration//GEN-END:variables
}
