/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package configuracao;

import database.Database;
import java.awt.BorderLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Ana Julia
 */
public class frmQuestionarioDinamico extends javax.swing.JFrame {
//o que faz aqui? p esses -1,-1, 1 e 5???  
    private int idQuestionarioRespostaCabInclusao = -1; //Inicializa a variável com um valor menor que 0 somente válido para distinguir que não é um registro do banco.
    public int idQuestionarioResposta = -1; //Inicializa a variável com um valor menor que 0 somente válido para distinguir que não é um registro do banco.
    private int ordem = 1; //Ordem inicial.
    public int idQuestionario = 1;  //Id do questionario inicial
    private int totalPerguntas = 5; //Quantidade total de perguntas.

    /**
     * Creates new form frmQuestionario
     */
    public frmQuestionarioDinamico() {
        initComponents();
        JButton button = new JButton("Exit");

        getContentPane().add(button, BorderLayout.NORTH);
        atualizarPergunta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTitulo = new javax.swing.JTextField();
        txtAutor = new javax.swing.JTextField();
        lblPergunta = new javax.swing.JLabel();
        txtResposta = new javax.swing.JTextField();
        btnProximo = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtDica = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Inclusão de perguntas para o Cenário");

        jLabel1.setText("Título");
        jLabel1.setName("lblTitulo"); // NOI18N

        jLabel2.setText("Autor");
        jLabel2.setName("lblAutor"); // NOI18N

        txtTitulo.setName("txtTitulo"); // NOI18N

        txtAutor.setName("txtAutor"); // NOI18N

        lblPergunta.setText("1.\tNo arquivo de configuração no parâmetro ServerAdminé permitido ao usuário notificar um erro ao administrador?");
        lblPergunta.setToolTipText("");
        lblPergunta.setName("lblPergunta1"); // NOI18N

        txtResposta.setName("txtResposta"); // NOI18N

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configuracao/salvar.png"))); // NOI18N
        btnProximo.setText("Salvar e Próximo");
        btnProximo.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProximo.setName("btnProximo"); // NOI18N
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        txtDica.setColumns(20);
        txtDica.setRows(5);
        txtDica.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        txtDica.setEnabled(false);
        txtDica.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(txtDica);

        jLabel4.setText("Dica");
        jLabel4.setName("lblDica"); // NOI18N

        btnSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/configuracao/cancelar.png"))); // NOI18N
        btnSair.setText("Cancelar");
        btnSair.setName("btnSair"); // NOI18N
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPergunta)
                            .addComponent(jLabel4))
                        .addGap(0, 67, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResposta)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtAutor)))
                            .addComponent(jScrollPane2)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(btnProximo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSair)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblPergunta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtResposta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnProximo)
                    .addComponent(btnSair)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void incluirCabecalho() {
        if (idQuestionarioRespostaCabInclusao != -1) {
            return;
        }

        Database db = new Database();
        Connection conn = db.abrirBanco();
        //titulo, descricao, autor        
        String insert = "insert into questionariorespostacab (titulo,autor) values (?,?)"; //NOI18N

        PreparedStatement stmt;
        try {
            stmt = conn.prepareStatement(insert, new String[]{"IDQUESTIONARIORESPOSTA"});
            stmt.setString(1, txtTitulo.getText());
            stmt.setString(2, txtAutor.getText());

            stmt.execute();
            ResultSet rs = stmt.getGeneratedKeys();
            if (rs.next()) {
                idQuestionarioRespostaCabInclusao = rs.getInt(1);
            }
        } catch (SQLException ex) {
            Logger.getLogger(frmCadastroArquivo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void gravarItem() 
	{
        if (idQuestionarioRespostaCabInclusao == -1) 
		{
            incluirCabecalho();
        }

        Database db = new Database();
        Connection conn = db.abrirBanco();
        //titulo, descricao, autor        
        String insert = "insert into questionariorespostaitem (idquestionarioresposta, idquestionario, resposta) values (?,?,?)"; //NOI18N

        PreparedStatement stmt;
        try 
		{
            stmt = conn.prepareStatement(insert, new String[]{"IDQUESTIONARIORESPOSTAITEM"});
            stmt.setInt(1, idQuestionarioRespostaCabInclusao);
            stmt.setInt(2, idQuestionario);
            stmt.setString(3, txtResposta.getText());

            stmt.execute();

            conn.close();
        } 
		catch (SQLException ex) 
		{
            Logger.getLogger(frmCadastroArquivo.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void atualizarPergunta() {
        try {
            Database db = new Database();
            Connection conn = db.abrirBanco();

            Statement sta = conn.createStatement();

            String sql = "";

            ResultSet resQtd = sta.executeQuery("select count(*) as totalQuestoes from questionario");

			//Pega o total de perguntas.
            while (resQtd.next()) {
                totalPerguntas = resQtd.getInt("totalQuestoes");
                break;
            }

            if (idQuestionarioResposta != -1) {
                sql = " SELECT QUESTIONARIO.IDQUESTIONARIO,"
                        + "        QUESTIONARIO.PERGUNTA, "
                        + "        QUESTIONARIO.DICA,"
                        + "        QUESTIONARIO.NROORDEM, "
                        + "        QUESTIONARIORESPOSTAITEM.IDQUESTIONARIORESPOSTAITEM,  "
                        + "        QUESTIONARIORESPOSTAITEM.RESPOSTA  "
                        + " FROM QUESTIONARIO "
                        + " LEFT JOIN QUESTIONARIORESPOSTAITEM ON QUESTIONARIORESPOSTAITEM.IDQUESTIONARIO = QUESTIONARIO.IDQUESTIONARIO"
                        + " WHERE QUESTIONARIO.IDQUESTIONARIO = " + String.valueOf(idQuestionario) + " AND "
                        + " QUESTIONARIO.NROORDEM = " + String.valueOf(ordem) + " AND "
                        + " QUESTIONARIORESPOSTAITEM.IDQUESTIONARIORESPOSTA = " + String.valueOf(idQuestionarioResposta);
            } else {
                sql = " SELECT QUESTIONARIO.IDQUESTIONARIO,"
                        + "        QUESTIONARIO.PERGUNTA, "
                        + "        QUESTIONARIO.DICA,"
                        + "        QUESTIONARIO.NROORDEM "
                        + " FROM QUESTIONARIO "
                        + //" WHERE QUESTIONARIO.IDQUESTIONARIO = " + String.valueOf(idQuestionario) + " AND " +
                        " WHERE QUESTIONARIO.NROORDEM = " + String.valueOf(ordem);
            }

            // getting the data back
            ResultSet res = sta.executeQuery(sql);

            while (res.next()) {
                idQuestionario = res.getInt("idquestionario");
                lblPergunta.setText(res.getString("Pergunta"));
                txtDica.setText(res.getString("dica"));

                if (idQuestionarioResposta != -1) {
                    txtResposta.setText(res.getString("RESPOSTA"));
                } else {
                    txtResposta.setText("");
                }
                //lembre-se um "" para cada coluna na tabela               
                /*res.getInt("IDCONFIGCAB");
                 res.getString("TITULO");
                 res.getString("DESCRICAO");
                 res.getString("AUTOR");
                 res.getDate("DATAINCLUSAO");*/
                break;
            }
            res.close();

            sta.close();
            conn.close();

        } catch (Exception e) {
            System.err.println("Exception: " + e.getMessage());
        }
    }

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed

        gravarItem();

        if (ordem == totalPerguntas) {
            this.setVisible(false);
            return;
        }


        ordem++;
        atualizarPergunta();
    }//GEN-LAST:event_btnProximoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmQuestionarioDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmQuestionarioDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmQuestionarioDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmQuestionarioDinamico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmQuestionarioDinamico().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnProximo;
    private javax.swing.JButton btnSair;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblPergunta;
    private javax.swing.JTextField txtAutor;
    private javax.swing.JTextArea txtDica;
    private javax.swing.JTextField txtResposta;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
