/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LAPLACE.java
 *
 * Created on 21/02/2011, 08:39:48
 */
package Laplace;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Diano
 */
public class LAPLACEWIN extends javax.swing.JFrame {

    /** Creates new form LAPLACE */
    private CalculaD calc = new CalculaD();
    private DefaultTableModel modeloTabela;
    private int[][] MatrizPrincipal;
    private int ordemMatriz = 0;

    public LAPLACEWIN() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton_novovetor = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable_matriz = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_determinante = new javax.swing.JTextField();
        jButton_calcular = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teorema de Laplace");
        setResizable(false);
        getContentPane().setLayout(null);

        jButton_novovetor.setText("Novo Vetor");
        jButton_novovetor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_novovetorActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_novovetor);
        jButton_novovetor.setBounds(10, 10, 130, 27);

        jTable_matriz.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable_matriz.setColumnSelectionAllowed(true);
        jTable_matriz.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable_matriz);
        jTable_matriz.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(40, 60, 620, 350);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 12));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Preencha a Tabela com a sua Matriz !");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 30, 360, 20);

        jLabel2.setText("Determinante");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(160, 430, 100, 20);

        jTextField_determinante.setEditable(false);
        getContentPane().add(jTextField_determinante);
        jTextField_determinante.setBounds(270, 430, 110, 25);

        jButton_calcular.setText("Calcular!");
        jButton_calcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_calcularActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_calcular);
        jButton_calcular.setBounds(420, 430, 120, 27);

        java.awt.Dimension screenSize = java.awt.Toolkit.getDefaultToolkit().getScreenSize();
        setBounds((screenSize.width-716)/2, (screenSize.height-516)/2, 716, 516);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_novovetorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_novovetorActionPerformed
        // TODO add your handling code here:
        ordemMatriz = Integer.parseInt(javax.swing.JOptionPane.showInputDialog(null, "Qual a ordem de seu Vetor: nxn"));
        criandoMatriz(ordemMatriz);
        jTextField_determinante.setText("NovoVetor");
    }//GEN-LAST:event_jButton_novovetorActionPerformed

    private void jButton_calcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_calcularActionPerformed
        // TODO add your handling code here:
        for (int l = 0; l < ordemMatriz; l++) {
            for (int c = 0; c < ordemMatriz; c++) {
                MatrizPrincipal[l][c] = Integer.parseInt(String.valueOf(jTable_matriz.getValueAt(l, c)));
            }
        }
        if (MatrizPrincipal.length == 1) {
            jTextField_determinante.setText(String.valueOf(("Matriz de ordem 1??!!! Tá de brincadeira!! - " + String.valueOf(jTable_matriz.getValueAt(0, 0)))));
        } else {
            jTextField_determinante.setText(String.valueOf(calc.calcularDeterminante(MatrizPrincipal)));
        }
    }//GEN-LAST:event_jButton_calcularActionPerformed


    private void criandoMatriz(int x) {
        MatrizPrincipal = new int[ordemMatriz][ordemMatriz];
        modeloTabela = new DefaultTableModel();
        for (int aux = 1; aux <= x; aux++) {
            modeloTabela.addColumn("Coluna" + aux);
        }
        modeloTabela.setNumRows(x);
        jTable_matriz.setModel(modeloTabela);
        for (int l = 0; l < ordemMatriz; l++) {
            for (int c = 0; c < ordemMatriz; c++) {
                jTable_matriz.setValueAt(0, l, c);
            }
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new LAPLACEWIN().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_calcular;
    private javax.swing.JButton jButton_novovetor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable_matriz;
    private javax.swing.JTextField jTextField_determinante;
    // End of variables declaration//GEN-END:variables
}
